### ISSUE TITLE
pretrained model was wrong

### ISSUE THREAD

**Issue by jjldr** [AICPS/roadscene2vec#10]
Hi, I found the pretrained model that you provide is not right. I use Netron to visualize the pretrained model, model is incomplete， the FastRGCNConv module is lost. And I found the def save_model(self) in trainer.py is wrong, the function can not save the whole model weight, could you please fix it, thank you.
<img width="737" alt="image" src="https://user-images.githubusercontent.com/33213158/203314765-b10feb91-af79-4437-84df-c3fe1fa42506.png">

**Comment by malawada** [comment]
Thanks for finding this bug. We resolved it by adding the RGCNConv layers to an nn.ModuleList. The layers properly register with PyTorch now. We will upload new pretrained models soon.

**Comment by jjldr** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by malawada** [comment]
We updated our pretrained models to use the full model weights after the fix. Please try the new models and let us know if they work for you.
