### ISSUE TITLE
where is the bev.json file come from?

### ISSUE THREAD

**Issue by GELIELEO** [AICPS/roadscene2vec#13]
I can not find it in the HDD dataset

**Comment by malawada** [comment]
Hello, thank you for your question. We generate the bev.json file using the BEV visualizer located here:
https://github.com/AICPS/roadscene2vec/tree/main/roadscene2vec/scene_graph/extraction/bev
Please follow the instructions there to calibrate your BEV projection for the HDD. 

We also have some sample settings from our prior experiments if you want to just use those as a starting point. You can refer to the settings for the honda images and copy those into bev.json at the appropriate keys.
https://github.com/AICPS/roadscene2vec/blob/main/roadscene2vec/scene_graph/extraction/bev/old_settings.txt
