### ISSUE TITLE
Annotation Tool

### ISSUE THREAD

**Issue by yuchen2199** [AICPS/roadscene2vec#5]
Dear editor,
    Thank you for your brilliant work.  According to section 3.1 of your paper, your implement an annotation tool with a graphical user interface (GUI). However, I can not find the corresponding code in this project. Could you provide more information that how to use the annotation tool？ 
    Looking forward to your reply.

**Comment by hkaeley** [comment]
Hello! Apologies for the delayed response, but the annotator tool is located here: https://github.com/AICPS/roadscene2vec/blob/main/roadscene2vec/learning/util/annotator.py

The README overviewing all data generation, including the annotation tool, can be found here:
https://github.com/AICPS/roadscene2vec/blob/7cba377a9dac865af4b6410333c2d57743fde69d/roadscene2vec/data/gen/README.md

I am closing this issue with this comment, but please let us know if further clarification is required by opening a follow-up issue. Thank you for your interest in our project!

**Comment by Brandhsu** [comment]
Hi @hkaeley, would it be possible to move the annotator to [roadscene2vec/data/gen](https://github.com/AICPS/roadscene2vec/tree/main/roadscene2vec/data/gen) and [roadscene2vec/scene_graph/extraction/bev](https://github.com/AICPS/roadscene2vec/tree/main/roadscene2vec/scene_graph/extraction/bev) to [roadscene2vec/data](https://github.com/AICPS/roadscene2vec/tree/main/roadscene2vec/data)/bev. I think it will be helpful for other users wanting to bring their own dataset.

**Comment by hkaeley** [comment]
Yep no problem, I agree. I have just pushed the changes now.

**Comment by malawada** [comment]
@hkaeley in the roadscene2vec paper we reference that the BEV tool is in scene_graph/extraction/bev so I think we should keep that one there to align with the paper. The annotator can be moved though.

**Comment by hkaeley** [comment]
Ah, that makes sense. Just pushed a commit to move it back.
