### ISSUE TITLE
Some questions about raw data

### ISSUE THREAD

**Issue by yuzhijia1997** [AICPS/roadscene2vec#7]
Hello, thank you for providing excellent work about scene-graph! I am interested in your work, and I‘d like to ask that, could you provide the raw data in google drive? The source about IEEE dataport can not be downloaded free. It is more helpful to promote works in this field. Thank you again！

**Comment by malawada** [comment]
Hello, thank you for your interest in our work and for this suggestion. We will try to upload the dataset to google drive soon. It is a large dataset so it may take some time.

**Comment by malawada** [comment]
Hello, the raw data is now available on our google drive link under the raw data folder. Here is a direct link: https://drive.google.com/file/d/1rAjnsbDLT3eZ0zJ5CwGknfAju3bewNh9/view?usp=sharing

Best of luck with your research. We would appreciate if you could cite our paper if you find our code and datasets useful :)

**Comment by yuzhijia1997** [comment]
Thank you very much. I want to express the depth of my gratitude for your replay.
