### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by xinxinlv** [AICPS/roadscene2vec#8]
Hi！Thank you for your excellent work. In terms of use case 2, how can I get the pretrained model? I didn't find '/pretrained_models/mrgcn_sequence_classification_model.pt'.

**Comment by malawada** [comment]
Hello, we provide some pretrained model files in our use_case_data google drive folder. Our data for these use cases is there as well. 
https://drive.google.com/drive/folders/15Wvwh1k7ySr2YW6ZRDxnpcQOpMe3J5F1?usp=sharing

**Comment by xinxinlv** [comment]
Thank you very much！
