### ISSUE TITLE
Use_case_2.py error

### ISSUE THREAD

**Issue by Triple-L** [AICPS/roadscene2vec#9]
roadscene2vec/learning/util/trainer.py", line 40, in __init__
    if self.config.training_configuration["seed"] != None:
AttributeError: 'configuration' object has no attribute 'training_configuration'

pytorch: 1.10.0
torchvision: 0.11.1
cudatoolkit: 11.3.1

**Comment by malawada** [comment]
We can't reproduce the error ourselves, so we aren't sure what is happening in your training environment. Please share the code and commands you are using as well as some debug/pdb output, like the values contained within self.config and the value of self.config.training_configuration if you can produce it.
